name: license-check
on:
  push:
    branches: [main]
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install go-licence-detector
        run: go install go.elastic.co/go-licence-detector@v0.10.0

      - name: License check
        run: make license-check
